/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import bean.DanhMucBean;
import controller.ChuyenManHinhController;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.List;
import javax.swing.WindowConstants;
import controller.DangNhapController;
import dao.PhanQuyenDAO;
import dao.PhanQuyenDAOImpl;
import model.Quyen;

/**
 *
 * @author ASUS
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    public void showWindow() {
        this.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
//        this.setUndecorated(true);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    public MainJFrame() {
        initComponents();
        setTitle("Phần mềm quản lý cửa hàng ô tô");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/logo.png")));

        ChuyenManHinhController chuyenManHinhController = new ChuyenManHinhController(jPnView);
        chuyenManHinhController.setView(jPnBanHang, jLbBanHang);

        DangNhapController controllerDangNhap = new DangNhapController();

        PhanQuyenDAO phanQuyenDAO = new PhanQuyenDAOImpl();

        List<DanhMucBean> listItem = new ArrayList<>();

        listItem.add(new DanhMucBean("SanPham", jPnSanPham, jLbSanPham));
        listItem.add(new DanhMucBean("BanHang", jPnBanHang, jLbBanHang));
        listItem.add(new DanhMucBean("NhanVien", jPnNhanVien, jLbNhanVien));
        listItem.add(new DanhMucBean("KhachHang", jPnKhachHang, jLbKhachHang));
        listItem.add(new DanhMucBean("NhapHang", jPnNhapHang, jLbNhapHang));
        listItem.add(new DanhMucBean("NhaCungCap", jPnNhaCungCap, jLbNhaCungCap));
        listItem.add(new DanhMucBean("ThongKe", jPnThongKe, jLbThongKe));

        String chucVu = controllerDangNhap.taiKhoanLogin.getChucVu();

        String[] listQuanLy = {"Quản lý sản phẩm",
            "Quản lý hóa đơn",
            "Quản lý nhân viên",
            "Quản lý khách hàng",
            "Quản lý nhập hàng",
            "Quản lý nhà cung cấp",
            "Thống kê"};

        for (String quanLy : listQuanLy) {
            Quyen quyen = phanQuyenDAO.getQuyen(chucVu, quanLy);

            switch (quanLy) {
                case "Quản lý sản phẩm":
                    if (quyen.getRead() != 1) {
                        jPnSanPham.setVisible(false);
                    }
                    break;
                case "Quản lý hóa đơn":
                    if (quyen.getRead() != 1) {
                        jPnBanHang.setVisible(false);
                    }
                    break;
                case "Quản lý nhân viên":
                    if (quyen.getRead() != 1) {
                        jPnNhanVien.setVisible(false);
                    }
                    break;
                case "Quản lý khách hàng":
                    if (quyen.getRead() != 1) {
                        jPnKhachHang.setVisible(false);
                    }
                    break;
                case "Quản lý nhập hàng":
                    if (quyen.getRead() != 1) {
                        jPnNhapHang.setVisible(false);
                    }
                    break;
                case "Quản lý nhà cung cấp":
                    if (quyen.getRead() != 1) {
                        jPnNhaCungCap.setVisible(false);
                    }
                    break;
                case "Thống kê":
                    if (quyen.getRead() != 1) {
                        jPnThongKe.setVisible(false);
                    }
                    break;
                default:
                    throw new AssertionError();
            }
        }

        chuyenManHinhController.setEvent(listItem);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPnRoot = new javax.swing.JPanel();
        jPnMenu = new javax.swing.JPanel();
        jPnBanHang = new javax.swing.JPanel();
        jLbBanHang = new javax.swing.JLabel();
        jPnSanPham = new javax.swing.JPanel();
        jLbSanPham = new javax.swing.JLabel();
        jPnNhapHang = new javax.swing.JPanel();
        jLbNhapHang = new javax.swing.JLabel();
        jPnNhaCungCap = new javax.swing.JPanel();
        jLbNhaCungCap = new javax.swing.JLabel();
        jPnKhachHang = new javax.swing.JPanel();
        jLbKhachHang = new javax.swing.JLabel();
        jPnNhanVien = new javax.swing.JPanel();
        jLbNhanVien = new javax.swing.JLabel();
        jPnThongKe = new javax.swing.JPanel();
        jLbThongKe = new javax.swing.JLabel();
        jPnView = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPnMenu.setBackground(new java.awt.Color(33, 46, 52));
        jPnMenu.setForeground(new java.awt.Color(255, 255, 255));

        jPnBanHang.setBackground(new java.awt.Color(33, 46, 52));

        jLbBanHang.setBackground(new java.awt.Color(153, 255, 51));
        jLbBanHang.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLbBanHang.setForeground(new java.awt.Color(255, 255, 255));
        jLbBanHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icons/cart-73-32.png"))); // NOI18N
        jLbBanHang.setText("Bán hàng");

        javax.swing.GroupLayout jPnBanHangLayout = new javax.swing.GroupLayout(jPnBanHang);
        jPnBanHang.setLayout(jPnBanHangLayout);
        jPnBanHangLayout.setHorizontalGroup(
            jPnBanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnBanHangLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLbBanHang, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPnBanHangLayout.setVerticalGroup(
            jPnBanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnBanHangLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLbBanHang, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPnSanPham.setBackground(new java.awt.Color(33, 46, 52));

        jLbSanPham.setBackground(new java.awt.Color(102, 102, 0));
        jLbSanPham.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLbSanPham.setForeground(new java.awt.Color(255, 255, 255));
        jLbSanPham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icons/car-4-32.png"))); // NOI18N
        jLbSanPham.setText("Sản phẩm");

        javax.swing.GroupLayout jPnSanPhamLayout = new javax.swing.GroupLayout(jPnSanPham);
        jPnSanPham.setLayout(jPnSanPhamLayout);
        jPnSanPhamLayout.setHorizontalGroup(
            jPnSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnSanPhamLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLbSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPnSanPhamLayout.setVerticalGroup(
            jPnSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnSanPhamLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLbSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPnNhapHang.setBackground(new java.awt.Color(33, 46, 52));

        jLbNhapHang.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLbNhapHang.setForeground(new java.awt.Color(255, 255, 255));
        jLbNhapHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icons/product-32.png"))); // NOI18N
        jLbNhapHang.setText("Nhập hàng");

        javax.swing.GroupLayout jPnNhapHangLayout = new javax.swing.GroupLayout(jPnNhapHang);
        jPnNhapHang.setLayout(jPnNhapHangLayout);
        jPnNhapHangLayout.setHorizontalGroup(
            jPnNhapHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnNhapHangLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLbNhapHang, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPnNhapHangLayout.setVerticalGroup(
            jPnNhapHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnNhapHangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLbNhapHang, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPnNhaCungCap.setBackground(new java.awt.Color(33, 46, 52));

        jLbNhaCungCap.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLbNhaCungCap.setForeground(new java.awt.Color(255, 255, 255));
        jLbNhaCungCap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icons/agreement.png"))); // NOI18N
        jLbNhaCungCap.setText("Nhà cung cấp");

        javax.swing.GroupLayout jPnNhaCungCapLayout = new javax.swing.GroupLayout(jPnNhaCungCap);
        jPnNhaCungCap.setLayout(jPnNhaCungCapLayout);
        jPnNhaCungCapLayout.setHorizontalGroup(
            jPnNhaCungCapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnNhaCungCapLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLbNhaCungCap, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPnNhaCungCapLayout.setVerticalGroup(
            jPnNhaCungCapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnNhaCungCapLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLbNhaCungCap, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jPnKhachHang.setBackground(new java.awt.Color(33, 46, 52));

        jLbKhachHang.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLbKhachHang.setForeground(new java.awt.Color(255, 255, 255));
        jLbKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icons/id-card.png"))); // NOI18N
        jLbKhachHang.setText("Khách hàng");

        javax.swing.GroupLayout jPnKhachHangLayout = new javax.swing.GroupLayout(jPnKhachHang);
        jPnKhachHang.setLayout(jPnKhachHangLayout);
        jPnKhachHangLayout.setHorizontalGroup(
            jPnKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnKhachHangLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLbKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPnKhachHangLayout.setVerticalGroup(
            jPnKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnKhachHangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLbKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPnNhanVien.setBackground(new java.awt.Color(33, 46, 52));

        jLbNhanVien.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLbNhanVien.setForeground(new java.awt.Color(255, 255, 255));
        jLbNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icons/user-32.png"))); // NOI18N
        jLbNhanVien.setText("Nhân viên");

        javax.swing.GroupLayout jPnNhanVienLayout = new javax.swing.GroupLayout(jPnNhanVien);
        jPnNhanVien.setLayout(jPnNhanVienLayout);
        jPnNhanVienLayout.setHorizontalGroup(
            jPnNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnNhanVienLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLbNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPnNhanVienLayout.setVerticalGroup(
            jPnNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnNhanVienLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLbNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPnThongKe.setBackground(new java.awt.Color(33, 46, 52));

        jLbThongKe.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLbThongKe.setForeground(new java.awt.Color(255, 255, 255));
        jLbThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icons/analytics-32.png"))); // NOI18N
        jLbThongKe.setText("Thống kê");

        javax.swing.GroupLayout jPnThongKeLayout = new javax.swing.GroupLayout(jPnThongKe);
        jPnThongKe.setLayout(jPnThongKeLayout);
        jPnThongKeLayout.setHorizontalGroup(
            jPnThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnThongKeLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLbThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPnThongKeLayout.setVerticalGroup(
            jPnThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnThongKeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLbThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPnMenuLayout = new javax.swing.GroupLayout(jPnMenu);
        jPnMenu.setLayout(jPnMenuLayout);
        jPnMenuLayout.setHorizontalGroup(
            jPnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnBanHang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPnSanPham, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPnNhaCungCap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPnNhanVien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPnKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPnNhapHang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPnThongKe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPnMenuLayout.setVerticalGroup(
            jPnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnMenuLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPnBanHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPnSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPnNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPnKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPnNhapHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPnNhaCungCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPnThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPnViewLayout = new javax.swing.GroupLayout(jPnView);
        jPnView.setLayout(jPnViewLayout);
        jPnViewLayout.setHorizontalGroup(
            jPnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 828, Short.MAX_VALUE)
        );
        jPnViewLayout.setVerticalGroup(
            jPnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 687, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPnRootLayout = new javax.swing.GroupLayout(jPnRoot);
        jPnRoot.setLayout(jPnRootLayout);
        jPnRootLayout.setHorizontalGroup(
            jPnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnRootLayout.createSequentialGroup()
                .addComponent(jPnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPnView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPnRootLayout.setVerticalGroup(
            jPnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPnView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1093, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPnRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 687, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPnRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLbBanHang;
    private javax.swing.JLabel jLbKhachHang;
    private javax.swing.JLabel jLbNhaCungCap;
    private javax.swing.JLabel jLbNhanVien;
    private javax.swing.JLabel jLbNhapHang;
    private javax.swing.JLabel jLbSanPham;
    private javax.swing.JLabel jLbThongKe;
    private javax.swing.JPanel jPnBanHang;
    private javax.swing.JPanel jPnKhachHang;
    private javax.swing.JPanel jPnMenu;
    private javax.swing.JPanel jPnNhaCungCap;
    private javax.swing.JPanel jPnNhanVien;
    private javax.swing.JPanel jPnNhapHang;
    private javax.swing.JPanel jPnRoot;
    private javax.swing.JPanel jPnSanPham;
    private javax.swing.JPanel jPnThongKe;
    private javax.swing.JPanel jPnView;
    // End of variables declaration//GEN-END:variables
}
