/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import controller.ThongKeController;
import java.awt.BorderLayout;
import java.awt.GridLayout;

/**
 *
 * @author ASUS
 */
public class ThongKeJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ThongKeJPanel
     */
    public ThongKeJPanel() {
        initComponents();
        
        ThongKeController controller = new ThongKeController(jLbTongOTo, jLbTongPhuTung, jLbTongKhachHang, jLbTongDoanhThu, 
        jCbNam, jLbQuy1, jLbQuy2, jLbQuy3, jLbQuy4, jLbDoanhThuNam, jTbTopSP, jPnChart, jPnChart2);
        
        controller.setDataToView();
        controller.setEvent();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPnOTo = new javax.swing.JPanel();
        jLbTongOTo = new javax.swing.JLabel();
        jLbOTo = new javax.swing.JLabel();
        jPnPhuTung = new javax.swing.JPanel();
        jLbTongPhuTung = new javax.swing.JLabel();
        jLbPhuTung = new javax.swing.JLabel();
        jPnKhachHang = new javax.swing.JPanel();
        jLbTongKhachHang = new javax.swing.JLabel();
        jLbKhachHang = new javax.swing.JLabel();
        jPnDoanhThu = new javax.swing.JPanel();
        jLbTongDoanhThu = new javax.swing.JLabel();
        jLbDoanhThu = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLbQuy1 = new javax.swing.JLabel();
        jLbQuy2 = new javax.swing.JLabel();
        jLbQuy3 = new javax.swing.JLabel();
        jLbQuy4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLbDoanhThuNam = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jCbNam = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTbTopSP = new javax.swing.JTable();
        jPnChart = new javax.swing.JPanel();
        jPnChart2 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));

        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jPnOTo.setBackground(new java.awt.Color(52, 58, 61));
        jPnOTo.setPreferredSize(new java.awt.Dimension(200, 135));

        jLbTongOTo.setBackground(new java.awt.Color(52, 58, 61));
        jLbTongOTo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLbTongOTo.setForeground(new java.awt.Color(255, 255, 255));
        jLbTongOTo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLbOTo.setBackground(new java.awt.Color(52, 58, 61));
        jLbOTo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLbOTo.setForeground(new java.awt.Color(255, 255, 255));
        jLbOTo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbOTo.setText("Ô tô trong cửa hàng");
        jLbOTo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPnOToLayout = new javax.swing.GroupLayout(jPnOTo);
        jPnOTo.setLayout(jPnOToLayout);
        jPnOToLayout.setHorizontalGroup(
            jPnOToLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLbOTo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
            .addComponent(jLbTongOTo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPnOToLayout.setVerticalGroup(
            jPnOToLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnOToLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLbOTo)
                .addGap(21, 21, 21)
                .addComponent(jLbTongOTo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        jPnPhuTung.setBackground(new java.awt.Color(52, 58, 61));

        jLbTongPhuTung.setBackground(new java.awt.Color(52, 58, 61));
        jLbTongPhuTung.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLbTongPhuTung.setForeground(new java.awt.Color(255, 255, 255));
        jLbTongPhuTung.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLbPhuTung.setBackground(new java.awt.Color(52, 58, 61));
        jLbPhuTung.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLbPhuTung.setForeground(new java.awt.Color(255, 255, 255));
        jLbPhuTung.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbPhuTung.setText("Phụ tùng");
        jLbPhuTung.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPnPhuTungLayout = new javax.swing.GroupLayout(jPnPhuTung);
        jPnPhuTung.setLayout(jPnPhuTungLayout);
        jPnPhuTungLayout.setHorizontalGroup(
            jPnPhuTungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLbTongPhuTung, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLbPhuTung, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );
        jPnPhuTungLayout.setVerticalGroup(
            jPnPhuTungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnPhuTungLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLbPhuTung)
                .addGap(21, 21, 21)
                .addComponent(jLbTongPhuTung, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPnKhachHang.setBackground(new java.awt.Color(52, 58, 61));

        jLbTongKhachHang.setBackground(new java.awt.Color(52, 58, 61));
        jLbTongKhachHang.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLbTongKhachHang.setForeground(new java.awt.Color(255, 255, 255));
        jLbTongKhachHang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLbKhachHang.setBackground(new java.awt.Color(52, 58, 61));
        jLbKhachHang.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLbKhachHang.setForeground(new java.awt.Color(255, 255, 255));
        jLbKhachHang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbKhachHang.setText("Khách hàng");

        javax.swing.GroupLayout jPnKhachHangLayout = new javax.swing.GroupLayout(jPnKhachHang);
        jPnKhachHang.setLayout(jPnKhachHangLayout);
        jPnKhachHangLayout.setHorizontalGroup(
            jPnKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLbTongKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLbKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );
        jPnKhachHangLayout.setVerticalGroup(
            jPnKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnKhachHangLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLbKhachHang)
                .addGap(21, 21, 21)
                .addComponent(jLbTongKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        jPnDoanhThu.setBackground(new java.awt.Color(52, 58, 61));
        jPnDoanhThu.setForeground(new java.awt.Color(255, 255, 255));

        jLbTongDoanhThu.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLbTongDoanhThu.setForeground(new java.awt.Color(255, 255, 255));
        jLbTongDoanhThu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLbDoanhThu.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLbDoanhThu.setForeground(new java.awt.Color(255, 255, 255));
        jLbDoanhThu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbDoanhThu.setText("Tổng doanh thu");
        jLbDoanhThu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPnDoanhThuLayout = new javax.swing.GroupLayout(jPnDoanhThu);
        jPnDoanhThu.setLayout(jPnDoanhThuLayout);
        jPnDoanhThuLayout.setHorizontalGroup(
            jPnDoanhThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLbDoanhThu, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
            .addComponent(jLbTongDoanhThu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPnDoanhThuLayout.setVerticalGroup(
            jPnDoanhThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnDoanhThuLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLbDoanhThu)
                .addGap(21, 21, 21)
                .addComponent(jLbTongDoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel3.setMinimumSize(new java.awt.Dimension(185, 132));
        jPanel3.setPreferredSize(new java.awt.Dimension(671, 75));

        jPanel4.setPreferredSize(new java.awt.Dimension(671, 75));
        jPanel4.setLayout(new java.awt.GridLayout(1, 5));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Quý");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.add(jLabel1);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Quý 1");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.add(jLabel2);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Quý 2");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.add(jLabel3);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Quý 3");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.add(jLabel4);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Quý 4");
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.add(jLabel10);

        jPanel5.setPreferredSize(new java.awt.Dimension(128, 37));
        jPanel5.setLayout(new java.awt.GridLayout(1, 0));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Doanh thu");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(jLabel5);

        jLbQuy1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLbQuy1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbQuy1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(jLbQuy1);

        jLbQuy2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLbQuy2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbQuy2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(jLbQuy2);

        jLbQuy3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLbQuy3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbQuy3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(jLbQuy3);

        jLbQuy4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLbQuy4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbQuy4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(jLbQuy4);

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLbDoanhThuNam.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLbDoanhThuNam.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbDoanhThuNam.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Tổng cộng");
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLbDoanhThuNam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLbDoanhThuNam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jCbNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbNamActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jCbNam, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCbNam, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPnKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPnOTo, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(97, 97, 97)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPnPhuTung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPnDoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 797, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPnOTo, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                    .addComponent(jPnPhuTung, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(68, 68, 68)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPnDoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPnKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 292, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
                .addGap(309, 309, 309))
        );

        jTabbedPane1.addTab("Tổng quát", jPanel1);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel6.setText("Top 5 sản phẩm bán chạy");

        jScrollPane1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jTbTopSP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTbTopSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã SP", "Tên", "Đã bán"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTbTopSP);

        jPnChart.setBackground(new java.awt.Color(153, 255, 153));

        javax.swing.GroupLayout jPnChartLayout = new javax.swing.GroupLayout(jPnChart);
        jPnChart.setLayout(jPnChartLayout);
        jPnChartLayout.setHorizontalGroup(
            jPnChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 874, Short.MAX_VALUE)
        );
        jPnChartLayout.setVerticalGroup(
            jPnChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 516, Short.MAX_VALUE)
        );

        jPnChart2.setBackground(new java.awt.Color(204, 255, 204));

        javax.swing.GroupLayout jPnChart2Layout = new javax.swing.GroupLayout(jPnChart2);
        jPnChart2.setLayout(jPnChart2Layout);
        jPnChart2Layout.setHorizontalGroup(
            jPnChart2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPnChart2Layout.setVerticalGroup(
            jPnChart2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 339, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPnChart2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 874, Short.MAX_VALUE)
                    .addComponent(jPnChart, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(51, 51, 51))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jPnChart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jPnChart2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(328, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel2);

        jTabbedPane1.addTab("Chi tiết", jScrollPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Tổng quát");
    }// </editor-fold>//GEN-END:initComponents

    private void jCbNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbNamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCbNamActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jCbNam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLbDoanhThu;
    private javax.swing.JLabel jLbDoanhThuNam;
    private javax.swing.JLabel jLbKhachHang;
    private javax.swing.JLabel jLbOTo;
    private javax.swing.JLabel jLbPhuTung;
    private javax.swing.JLabel jLbQuy1;
    private javax.swing.JLabel jLbQuy2;
    private javax.swing.JLabel jLbQuy3;
    private javax.swing.JLabel jLbQuy4;
    private javax.swing.JLabel jLbTongDoanhThu;
    private javax.swing.JLabel jLbTongKhachHang;
    private javax.swing.JLabel jLbTongOTo;
    private javax.swing.JLabel jLbTongPhuTung;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPnChart;
    private javax.swing.JPanel jPnChart2;
    private javax.swing.JPanel jPnDoanhThu;
    private javax.swing.JPanel jPnKhachHang;
    private javax.swing.JPanel jPnOTo;
    private javax.swing.JPanel jPnPhuTung;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTbTopSP;
    // End of variables declaration//GEN-END:variables
}
